Fantasy's Furniture
VM-Chinese-translate-group/fantasy-realm pull request #18
Opened 2023-09-05 14:31 UTC by nageih

2023-09-05 14:34 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.fairy_lights_1": "小精灵的灯  (1)",
半角符号

2023-09-05 14:34 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.presents_stack_2": "礼物堆 (2)",
半角符号

2023-09-05 14:35 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.venthyr_widow_bloom": "Widowbloom（魔兽世界）花瓶",
漏译

2023-09-05 14:37 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "text.fantasyfurniture.recipe.accepts_any": "可使用的: %s"
建议：

> 接受任意：%s

或者

> 接受任一：%s

2023-09-05 14:37 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.venthyr.bed_double": "温西尔（魔兽世界）的双人床",
无意义的标注

2023-09-05 14:38 UTC, 3093FengMing reviewed
审核1

2023-09-05 15:13 UTC, dwadfawf commented
已修改

2023-09-06 16:43 UTC, 502y requested changes
根据标点符号用法规范，括号前无需额外添加空格

2023-09-06 16:43 UTC, 502y commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.presents_stack_1": "礼物堆 (1)",
```suggestion
  "block.fantasyfurniture.decorations.presents_stack_1": "礼物堆（1）",
```
多余的空格和错误的半角符号

2023-09-06 16:43 UTC, 502y commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.presents_stack_2": "礼物堆 (2)",
```suggestion
  "block.fantasyfurniture.decorations.presents_stack_2": "礼物堆（2）",
```
多余的空格和错误的半角符号

2023-09-06 16:43 UTC, 502y commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.fairy_lights_2": "小精灵的灯 (2)",
```suggestion
  "block.fantasyfurniture.decorations.dunmer_pottery_0": "黑暗精灵的陶器（1）",
  "block.fantasyfurniture.decorations.dunmer_pottery_1": "黑暗精灵的陶器（2）",
  "block.fantasyfurniture.decorations.fairy_lights_1": "小精灵的灯（1）",
  "block.fantasyfurniture.decorations.fairy_lights_2": "小精灵的灯（2）",
```
多余的空格和错误的半角符号

2023-09-06 16:43 UTC, 502y commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.decorations.venthyr_food_1": "温西尔的食物 （2）",
```suggestion
  "block.fantasyfurniture.decorations.venthyr_food_0": "温西尔的食物（1）",
  "block.fantasyfurniture.decorations.venthyr_food_1": "温西尔的食物（2）",
```
多余的空格

2023-09-06 16:43 UTC, 502y commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.necrolord.desk_right": "死灵领主的书桌 （右）",
```suggestion
  "block.fantasyfurniture.necrolord.desk_right": "死灵领主的书桌（右）",
```
多余的空格

2023-09-06 16:43 UTC, 502y commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.nordic.desk_right": "北欧人的书桌 （右）",
```suggestion
  "block.fantasyfurniture.nordic.desk_right": "北欧人的书桌（右）",
```
多余的空格

2023-09-06 16:43 UTC, 502y commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.royal.desk_right": "皇家书桌 （右）",
```suggestion
  "block.fantasyfurniture.royal.desk_right": "皇家书桌（右）",
```
多余的空格

2023-09-06 16:43 UTC, 502y commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.royal.door_double": "皇家 双扇门",
```suggestion
  "block.fantasyfurniture.royal.door_double": "皇家双扇门",
```
多余的空格

2023-09-06 16:43 UTC, 502y commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.venthyr.desk_right": "温西尔的书桌 （右）",
```suggestion
  "block.fantasyfurniture.venthyr.desk_right": "温西尔的书桌（右）",
```
多余的空格

2023-09-07 12:44 UTC, 3093FengMing reviewed
修正1

2023-09-07 12:44 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "itemGroup.category.necrolord": "死灵领主的",
category应当是一个名词/动词而不是形容词，
考虑“死灵领主类”或”死灵领主的家具“

2023-09-07 12:44 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "itemGroup.category.dunmer": "暗精灵的",
category应当是一个名词/动词而不是形容词，
考虑“暗精灵类”或”暗精灵的家具“

2023-09-07 12:44 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "itemGroup.category.nordic": "北欧人的",
category应当是一个名词/动词而不是形容词，
考虑“北欧类”

2023-09-07 12:44 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "itemGroup.category.venthyr": "温西尔的",
category应当是一个名词/动词而不是形容词，
考虑“温西尔类”或”温西尔的家具“

2023-09-07 12:44 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "block.fantasyfurniture.nordic.door_double": "北欧人的 双扇门",
无意义的空格

2023-09-07 12:44 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "itemGroup.category.bone": "骨制",
category应当是一个名词/动词而不是形容词，
考虑“骨制家具“

2023-09-07 12:44 UTC, 3093FengMing commented on Patch-Pack-CN/config/paxi/resourcepacks/vm-language/assets/fantasyfurniture/lang/zh_cn.json
> +  "itemGroup.category.decorations": "装饰品",
考虑”装饰“

2023-09-07 14:25 UTC, merged