汉化[蔚蓝浩空]
VM-Chinese-translate-group/fantasy-realm pull request #20
Opened 2023-09-05 18:28 UTC by Nothingness-Void

2023-09-06 12:32 UTC, 3093FengMing reviewed
粗略的看了一下

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "建造一个极昼之崖传送门"
官译：永昼之地

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "&b极昼之崖&r传送门是由&2绿松石砖&r搭好框架，并用&c御风火石&r &2点燃得到的。 &c御风火石&r可从&2守门人&r处购买，传送门本体也在他的家中。"
官译：永昼之地，
建议改为：&b永昼之地&r传送门以&2绿松石砖&r作框架，可以用&c御风火石&r &2激活传送门。

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +				title: "建造一个&3极昼之崖传送门"
官译：永昼之地

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "&3恒晓之地&r传送门是由&2望舒石砖&r搭好框架，并用&c御风火石&r &2点燃得到的。&c御风火石&r可从&2守门人&r处购买，传送门本体也在他的家中。"
同上一句：
建议改为：&b恒晓之地&r传送门以&2绿松石砖&r作框架，可以用&c御风火石&r &2激活传送门。

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "从&2守门人&r那里获得&3浩蓝旅记&r。他会出现在&a平原, 山地&r，和 &a雪地生物群系&r。随着你在模组中的进度他也会解锁更多交易。"
“它”也会解锁更多交易。

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "换到一个&3星盘"
应使用：交易得到一个星盘
而不是口语

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "使你传送到星辰源处"
”允许你“传送到星辰源处

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "造一个&3 工具箱"
使用书面语而不是口语：”制作“一个&3 工具箱

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "在大范围内&c阻止地对生物&r&6生成&r。 本身不发光。"
"地对"？，应改为：在大范围内&c阻止敌对生物&r&6生成&r。本身不发光。

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +				title: "造一个&3珍珠灵匣"
制作

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "做一套&3天闪石工具"
制作

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "做一套&3透辉石工具"
制作

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "干掉召唤师"
”击杀“或”击败“，使用书面语而不是口语

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +				title: "干掉&3召唤师"
”击杀“或”击败“，使用书面语而不是口语

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +				title: "干掉&3炼金术士"
”击杀“或”击败“，使用书面语而不是口语

2023-09-06 12:32 UTC, 3093FengMing commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "可于&c惑乱地牢&r内找到。推荐装配&2透辉石 或 绛紫晶&r装备 和 &2月长石盾牌&r。 召唤BOSS需要四个&c惑乱钥匙&r可从&6地牢中的箱子&r中找到 或 在与钥匙孔方块互动后&6从守门人处购买&r。"
互动->交互

2023-09-06 15:39 UTC, DC10-10 requested changes

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "&2主世界装备&r不太好使。你可能需要打造一套全新的工具和护甲"
```suggestion
			subtitle: "&2主世界的装备&r不好使。你需要打造一套全新的工具和护甲。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "从&2守门人&r那里获得&3浩蓝旅记&r。他会出现在&a平原, 山地&r，和 &a雪地生物群系&r。随着你在模组中的进度他也会解锁更多交易。"
```suggestion
			subtitle: "从&2守门人&r那里获得&3浩蓝旅记&r。他会出现在&a平原、山地&r和&a雪地生物群系&r。随着你的进度的推进，他会解锁更多&6交易。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "&3恒晓之地&r传送门是由&2望舒石砖&r搭好框架，并用&c御风火石&r &2点燃得到的。&c御风火石&r可从&2守门人&r处购买，传送门本体也在他的家中。"
```suggestion
			subtitle: "&3恒晓之地&r传送门以&2望舒石砖&r作为框架，使用&c御风火石&r&2点燃&r以激活传送门。&c御风火石&r可从&2守门人&r处购买，传送门本体也在他的家中。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "&b永昼之地&r传送门是由&2绿松石砖&r搭好框架，并用&c御风火石&r &2点燃得到的。 &c御风火石&r可从&2守门人&r处购买，传送门本体也在他的家中。"
```suggestion
			subtitle: "&b永昼之地&r传送门以&2绿松石砖&r作为框架，使用&c御风火石&r点燃以激活传送门。&c御风火石&r可从&2守门人&r处购买，传送门本体也在他的家中。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "可将村民转化为观星者职业。"
```suggestion
			subtitle: "可将村民的职业转化为观星者。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "换到一个&3星盘"
```suggestion
			title: "交易得到一个&3星盘"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "使你传送到星辰源处"
```suggestion
			subtitle: "可将你传送到星辰源处。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "造一个&3 工具箱"
```suggestion
			title: "合成一个&3工具箱"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "使用&2缪铁锭&r&c给工具增加耐久&r。 也可用于&2切换工具上的手柄&r。不同工具使用不同的手柄会有不同效果。"
```suggestion
			subtitle: "使用&2缪铁锭&r&c给工具增加耐久&r。也可用于&2切换工具上的手柄&r。不同工具使用不同的手柄会有不同效果。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "在大范围内&c阻止敌对生物&r&6生成&r。 本身不发光。"
```suggestion
			subtitle: "在&6大范围内&r&c阻止敌对生物&r&6生成&r。本身不发光。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +				title: "造一个&3珍珠灵匣"
```suggestion
				title: "合成一个&3珍珠灵匣"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "制作一套&3天闪石工具"
```suggestion
			title: "合成一套&3天闪石工具"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "制作一套&3透辉石工具"
```suggestion
			title: "合成一套&3透辉石工具"
```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "制作一套&3绛紫晶工具"
```suggestion
			title: "合成一套&3绛紫晶工具"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "比&2透辉石&r速度快，但会弱一些。 绛紫晶矿&r&2深埋底下"
```suggestion
			subtitle: "比&2透辉石&r速度快，但更弱一些。绛紫晶矿&r&2深埋地下。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			title: "击杀召唤师"
```suggestion
			title: "击败召唤师"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "可于&c惑乱地牢&r内找到。推荐装配&2透辉石 或 绛紫晶&r装备 和 &2月长石盾牌&r。 召唤BOSS需要四个&c惑乱钥匙&r可从&6地牢中的箱子&r中找到 或 在与钥匙孔方块交互后&6从守门人处购买&r。"
```suggestion
			subtitle: "生成于&c惑乱地牢&r中。推荐使用&2透辉石或绛紫晶&r装备和&2月长石盾牌&r。召唤它需要四个&c惑乱钥匙&r，可在&6地牢中的箱子&r中找到，或在与钥匙孔方块交互后&6从守门人处购买&r。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +				title: "击杀&3召唤师"
```suggestion
				title: "击败&3召唤师"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "可于&c惑乱地牢&r内找到。推荐装配&2透辉石 或 绛紫晶&r装备 和 &2月长石盾牌&r。 召唤BOSS需要四个&c惑乱钥匙&r可从&6地牢中的箱子&r内找到 或 在与钥匙孔方块交互后&6从守门人处购买&r。掉落的遗物可用于&4复活BOSS。"
```suggestion
			subtitle: "生成于&c惑乱地牢&r中。推荐使用&2透辉石或绛紫晶&r装备和&2月长石盾牌&r。召唤它需要四个&c惑乱钥匙&r，可在&6地牢中的箱子&r内找到，或在与钥匙孔方块交互后&6从守门人处购买&r。掉落的遗物可用于&4复活BOSS。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +				title: "击杀&3炼金术士"
```suggestion
				title: "击败&3炼金术士"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "可于&c自然城堡&r内找到。推荐装配&2透辉石 或 绛紫晶&r装备 和 &2月长石盾牌&r。 同时，你也需要&c本模组中的斧子&r. 召唤BOSS需要四个&2天理钥匙&r， &2钥匙每层仅生成一个 也可在与&6钥匙孔方块&r交互后从守门人处购买&r 。 掉落的遗物可用于复活BOSS。"
```suggestion
			subtitle: "生成于&c自然城堡&r内。推荐使用&2透辉石或绛紫晶&r装备和&2月长石盾牌&r。同时，你还需要&c本维度中的斧子&r。召唤它需要四个&2天理钥匙&r，&2钥匙每层仅生成一个，也可在与&6顶层的钥匙孔方块&r交互后从守门人处购买&r。掉落的遗物可用于复活BOSS。"

```

2023-09-06 15:39 UTC, DC10-10 commented on Patch-Pack-CN/config/ftbquests/quests/chapters/blue_skies.snbt
> +			subtitle: "可于&2猛毒地牢&r内找到。 推荐装配&2透辉石 或 绛紫晶&r装备 和 &2月长石盾牌&r。 召唤BOSS需要四个&2猛毒钥匙&r，可从&6地牢中的箱子&r内找到 或 在与钥匙孔方块交互后&6从守门人处购买&r。 掉落的遗物可用于复活BOSS。"
```suggestion
			subtitle: "生成于&2猛毒地牢&r内。推荐使用&2透辉石或绛紫晶&r装备和&2月长石盾牌&r。召唤它需要四个&2猛毒钥匙&r，可在&6地牢中的箱子&r内找到，或在&6与底层的钥匙孔方块交互后从守门人处购买&r。掉落的遗物可用于复活BOSS。"

```

2023-09-07 12:34 UTC, nageih commented on Patch-Pack-CN/config/ftbquests/quests/chapters/ice__fire.snbt
> +	title: " &b冰 &f\\& &4火&r传说"
```suggestion
	title: " &b冰&r&4火&r传说"

```

2023-09-07 12:34 UTC, nageih commented on Patch-Pack-CN/config/ftbquests/quests/chapters/ice__fire.snbt
> +			title: "找到&b手稿t"
```suggestion
			title: "找到&b手稿"

```

2023-09-08 08:20 UTC, merged